In [248]:
# import necessory Libraries

import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
import tensorflow as tf
import keras
from tensorflow.keras.preprocessing.text import one_hot
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression

In [249]:
# load a spam  dataset 

data=pd.read_csv("H:\CodIt Solutions\SMS Spam Dataset/spam.csv", index_col=False)
data.head()

Unnamed: 0 spamORham                                            Message
0           0       ham  Go until jurong point, crazy.. Available only ...
1           1       ham                      Ok lar... Joking wif u oni...
2           2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3           3       ham  U dun say so early hor... U c already then say...
4           4       ham  Nah I don't think he goes to usf, he lives aro...

In [250]:
# remove extra column "Unnamed: 0"

data.drop("Unnamed: 0", axis=1, inplace=True)
data.head()

spamORham                                            Message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...

In [251]:
# we see random data and lenth of data

x=data['Message'][143]
print(len(x))
print(data['Message'][143])

42
I know you are. Can you pls open the back?


In [252]:
# convert a string into categorical value

LE=LabelEncoder()
y=LE.fit_transform(data['spamORham'])


In [253]:
# check how many ham and spam there in the dataset
# class are imbalance 

data['spamORham'].value_counts()

ham     4825
spam     747
Name: spamORham, dtype: int64

In [254]:
main_data=pd.concat([data['Message'], pd.Series(y)], axis=1, keys=['Message', 'spamORham'])

In [255]:
main_data.head()

Message  spamORham
0  Go until jurong point, crazy.. Available only ...          0
1                      Ok lar... Joking wif u oni...          0
2  Free entry in 2 a wkly comp to win FA Cup fina...          1
3  U dun say so early hor... U c already then say...          0
4  Nah I don't think he goes to usf, he lives aro...          0

In [256]:
#randomly take a ham in the dataset

ham=main_data[main_data['spamORham']==0].sample(n=747)
spam=main_data[main_data['spamORham']==1].sample(n=747)

In [257]:
sortdata=pd.concat([ham,spam], axis=0)

In [258]:
sortdata

Message  spamORham
4851                             I liked your new house          0
4707  Did you say bold, then torch later. Or one tor...          0
939   Better. Made up for Friday and stuffed myself ...          0
3487                Still i have not checked it da. . .          0
1321  I wake up long ago already... Dunno, what othe...          0
...                                                 ...        ...
787   Ever thought about living a good life with a p...          1
3190  UR awarded a City Break and could WIN a å£200 ...          1
3527  You are a å£1000 winner or Guaranteed Caller P...          1
146   FreeMsg Why haven't you replied to my text? I'...          1
2824  Congratulations - Thanks to a good friend U ha...          1

[1494 rows x 2 columns]

In [259]:
voc_size=1000000

In [260]:
#covert a word into vector using WordEmbedding

one_rep=[one_hot(words,voc_size)for words in sortdata.Message]

In [261]:
print(one_rep)

[[514385, 990995, 75028, 833665, 894945], [986182, 830897, 984061, 424700, 587024, 311504, 790210, 944760, 801221, 311504, 958744, 735141], [930612, 856298, 494178, 131236, 935514, 958744, 642121, 590826, 807376, 644351, 143724, 443475, 352862, 514385, 85288, 53265, 258583, 928617, 490876, 88482, 932701, 10786, 259589, 8721, 195306, 53265], [113655, 514385, 75489, 932701, 584759, 803684, 954821], [514385, 923791, 494178, 844746, 838519, 983636, 888244, 247155, 579246, 610404], [247155, 226786, 181934, 250918, 514520, 574538], [514385, 822918, 56775, 538433, 932448, 13080, 108486, 226432], [424872, 29650, 143724, 354665, 975911, 118663, 782443, 666975, 961219, 923791, 639876, 494178, 928617, 466837, 939247, 604483, 172158, 259504, 476522], [673490, 830897, 814016, 18820, 803684, 909121, 226786, 776128, 944760, 163757, 830897, 814016, 992330, 649353, 352755, 110736, 639876, 163757, 537428, 988888], [192607, 351432, 537285, 928617, 296869, 377402, 116667, 830897, 75489, 788724, 821657, 95

In [262]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [263]:
sent_length=150
emb_sequence=pad_sequences(one_rep, padding='pre', maxlen=sent_length)
print(emb_sequence)

[[     0      0      0 ...  75028 833665 894945]
 [     0      0      0 ... 311504 958744 735141]
 [     0      0      0 ...   8721 195306  53265]
 ...
 [     0      0      0 ... 544924 352862  23059]
 [     0      0      0 ... 127916 198309 147460]
 [     0      0      0 ... 826171 365116 539833]]


In [264]:
X_train, X_test, y_train, y_test=train_test_split(emb_sequence, sortdata['spamORham'], test_size=0.1, random_state=42)

In [265]:
from sklearn.ensemble import RandomForestClassifier

In [266]:
clf = RandomForestClassifier(max_depth=2, random_state=42)

In [267]:
clf.fit(X_train, y_train)

RandomForestClassifier(max_depth=2, random_state=42)

In [268]:
y_pred = model.predict(X_test)

print(y_test[:20])
print(y_pred[:20])

3637    1
3440    1
356     1
267     1
4018    1
872     0
126     0
2278    0
3969    0
1092    0
2472    1
997     0
263     1
3264    1
289     0
565     0
3441    1
88      0
3187    1
3143    0
Name: spamORham, dtype: int32
[1 1 1 1 1 0 0 0 1 0 1 1 1 1 1 1 1 0 1 0]


In [269]:
from sklearn.metrics import accuracy_score, classification_report

In [270]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.83


In [271]:
# Display the classification report
print("\nClassification Info:")
print(classification_report(y_test, y_pred))


Classification Info:
              precision    recall  f1-score   support

           0       0.86      0.79      0.82        75
           1       0.80      0.87      0.83        75

    accuracy                           0.83       150
   macro avg       0.83      0.83      0.83       150
weighted avg       0.83      0.83      0.83       150

